### ISSUE TITLE
GNU GPL doesn’t require users to publish changes

### ISSUE THREAD

**Issue by Simplaf234-ghost** [FrancescoBorzi/why-I-hate-wow-private-servers#14]
You say

> In simple words, this license says the following: use the code to do whatever you want, without paying anything, as long as any modification to the original code is also released under the same license. Basically, the license of these projects requires those who use them to publish any changes to the public.

but GNU _GPL_ does not require users to publish changes. It is only required if they release their emulator in binary form which private server operators don’t.

There is also GNU _AGPL_ which requires to publish source code if it is used on publicly available server, but it isn’t MaNGOS license.

**Comment by FrancescoBorzi** [comment]
Thanks for your concern @Simplaf234-ghost .

As I wrote in the [Disclaimer](https://github.com/FrancescoBorzi/why-I-hate-wow-private-servers#disclaimer-for-fellow-developers):

> I'm aware of GPL not being exactly like AGPL and I'm aware of the ASP loophole issue

The AGPL license has been created to solve this "issue". And I believe that kind of behaviour goes against the free software mentality, even if not strictly against the GPL (because of the loophole issue).

**Comment by Simplaf234-ghost** [comment]
It’s not GPL requirement anyway but you wrote it is.

I recommend you to fix it to say it is against free software _mentality_, not the _license_.

**Comment by FrancescoBorzi** [comment]
@Simplaf234-ghost https://github.com/FrancescoBorzi/why-I-hate-wow-private-servers/commit/03a349469a6b3fdbcc18c304e5c37d960a378d13

**Comment by Simplaf234-ghost** [comment]
Sentence from first message here is still not fixed.
